### ISSUE TITLE
失效部分

### ISSUE THREAD

**Issue by wangxiaodao** [rptec/rpv#2]
乐视 腾讯 华数 酷狗 爆米花 酷我 糖豆 失效了 ^_^

**Comment by rptec** [comment]
哦，由于公开分享，这版是我很早以前做的，，，
现在我自己的电影站 视频主要使用百度云及乐视云，，加上最近直比较忙，空闲时间较少。
解析的话 现在基本只维护优酷等少数站点，，，未来如果有时间的话回抽出来维护一下的。。。到时候会顺便公开我自己电影站现在正在使用的百度及乐视云api。。
